# Allow token clients to load icon directly
Access-Control-Allow-Origin = "*"

# xrp-ledger.toml for CFT

[[ISSUERS]]
address = "raMDb32m6b3BHJnBzZ6R5bMRDV5URsuCwx"
name = "Corporate Fuel"
website = "https://panorama2000.github.io/corporate-fuel/"
email = "panorama.2018@proton.me"

[[ISSUERS.TOKENS]]
code = "CFT"
name = "CFT"
description =  "Corporate Fuel (CFT) is a digital currency, developed specifically for the funding of our corporate setup and registration."
icon = "https://raw.githubusercontent.com/panorama2000/corporate-fuel/main/r99.png"
